export const DAILY_LIMIT_TIME_ZONE = "Asia/Tokyo"
export const DAILY_LIMIT_RESET_HOUR = 0
export const DAILY_LIMIT_RESET_MINUTE = 0
export const WEEKLY_LIMIT_RESET_DAY = 1

export const FREE_PLAN_DAILY_MESSAGE_LIMIT = 5
export const FREE_PLAN_MONTHLY_TOKEN_LIMIT = 60_000

export const PRO_PLAN_WEEKLY_TOKEN_LIMIT = 150_000
export const PRO_PLAN_ROLLING_30_DAY_TOKEN_LIMIT = 650_000

export const USAGE_WARNING_THRESHOLD_LOW = 0.8
export const USAGE_WARNING_THRESHOLD_HIGH = 0.95
