import type { Metadata } from "next";
import { Geist_Mono, Inter, Pacifico } from "next/font/google";
import { cookies } from "next/headers";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { I18nProvider } from "@/components/i18n/i18n-provider";
import {
  DEFAULT_THEME_PREFERENCE,
  THEME_PREFERENCE_COOKIE_KEY,
  parseThemePreference,
  type ThemePreference,
} from "@/lib/theme-preference";
import { resolveRequestLocale } from "@/lib/i18n/locale";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400",
  variable: "--font-pacifico",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const resolveInitialThemePreference = async (): Promise<ThemePreference> => {
  const cookieStore = await cookies()
  return parseThemePreference(
    cookieStore.get(THEME_PREFERENCE_COOKIE_KEY)?.value,
    DEFAULT_THEME_PREFERENCE
  )
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await resolveRequestLocale()
  const initialThemePreference = await resolveInitialThemePreference()
  return (
    <html
      lang={locale}
      className={initialThemePreference === "dark" ? "dark" : undefined}
      suppressHydrationWarning
    >
      <body
        className={`${inter.variable} ${pacifico.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider locale={locale}>
          <ThemeProvider initialThemePreference={initialThemePreference}>
            {children}
          </ThemeProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
