import type { Metadata } from "next";
import { Geist_Mono, Inter, Pacifico } from "next/font/google";
import { auth } from "@/auth";
import prisma from "@/lib/prisma";
import { ThemeProvider } from "@/components/theme/theme-provider";
import {
  DEFAULT_THEME_PREFERENCE,
  getStoredThemePreference,
  type ThemePreference,
} from "@/lib/theme-preference";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400",
  variable: "--font-pacifico",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const resolveInitialThemePreference = async (): Promise<ThemePreference> => {
  const session = await auth()
  if (!session?.user?.id) {
    return DEFAULT_THEME_PREFERENCE
  }

  try {
    return await getStoredThemePreference(prisma, session.user.id)
  } catch (error) {
    console.error("Failed to resolve initial theme preference:", error)
    return DEFAULT_THEME_PREFERENCE
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialThemePreference = await resolveInitialThemePreference()
  return (
    <html
      lang="en"
      className={initialThemePreference === "dark" ? "dark" : undefined}
      suppressHydrationWarning
    >
      <body
        className={`${inter.variable} ${pacifico.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider initialThemePreference={initialThemePreference}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
